name: Daily DigitalOcean Cost Alert

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # This allows the action to push changes

jobs:
  generate-cost-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate cost report
      env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
      run: python do_cost_alert.py
    
    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: Commit and push if changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update cost report for $(date +'%Y-%m-%d')" && git push)
